[versions]
kotlin-serialization-json = "1.9.0"
hiltNavigationCompose = "1.3.0"
materialIconsExtended = "1.7.8"
lifecycleRuntimeKtx = "2.9.4"
material3 = "1.5.0-alpha07"
activityCompose = "1.11.0"
composeBom = "2025.10.01"
splashScreen = "1.0.1"
coilCompose = "3.3.0"
coroutines = "1.10.2"
ksp = "2.2.20-2.0.3"
navigation = "2.9.5"
jwtdecode = "2.0.2"
datastore = "1.1.7"
coreKtx = "1.17.0"
kotlin = "2.2.20"
room = "2.8.3"
hilt = "2.57.2"
ktor = "3.3.1"
agp = "8.12.3"

[libraries]
ksp-gradle-plugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp"}
compose-gradle-plugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin"}
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp"}

androidx-material3-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
androidx-material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
androidx-ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui = { module = "androidx.compose.ui:ui" }

androidx-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashScreen" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }

hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-core = { module = "com.google.dagger:hilt-core", version.ref = "hilt" }

kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization-json" }
datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }

coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }

javax-inject = { module = "javax.inject:javax.inject", version = "1" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
jwt-decode = { module = "com.auth0.android:jwtdecode", version.ref = "jwtdecode"}

ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }

[plugins]
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

custom-android-application-compose = { id = "custom.android.application.compose" }
custom-android-library-compose = { id = "custom.android.library.compose" }
custom-android-feature-domain = { id = "custom.android.feature.domain" }
custom-android-application = { id = "custom.android.application" }
custom-android-library = { id = "custom.android.library" }
custom-android-feature = { id = "custom.android.feature" }
custom-jvm-library = { id = "custom.jvm.library" }
custom-hilt = { id = "custom.hilt" }

[bundles]
ktor = [
    "ktor-client-content-negotiation",
    "ktor-serialization-kotlinx-json",
    "ktor-client-logging",
    "ktor-client-android",
    "ktor-client-auth",
    "ktor-client-core"
]




